config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, sign_out_via: [ :post, :delete ]
  root 'projects#index'
  get 'tasks/:id/done', to: 'tasks#done', as: :set_task_done
  get 'projects/new_untitled', to: 'projects#new_untitled', as: :new_untitled_project

  post 'projects/save_sort', to: 'projects#save_sort', as: :save_sort

  resources :projects do
    resources :tasks
  end
 
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  
  validates :name, presence: true

  scope :ordered, -> { order('created_at ASC') }

  def ordered_tasks
    tasks.order(:rate)
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :name, presence: true
  validates :deadline, presence: true

  def done?
    self.done
  end

  def done!
    self.done = true
    save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_filter :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects.ordered
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.json { render json: @project }
      else
        format.html { render :action => "edit" }
        format.json { render json: @project }
      end
    end  
  end

  def delete
  end

  def destroy
    @project.destroy
    render nothing: true, status: :ok
  end

  def new_untitled
    @project = current_user.projects.new(name: 'Untitled')
    if @project.save
      render @project
    else
      render text: @project.errors.full_messages.join("\n"), status: :error      
    end
  end

  def save_sort
    params[:taskIds].each_with_index do |task_id, index|
      task = Task.find(task_id)
      task.rate = index
      task.save!
    end
    render nothing: true
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_project, except: [:done]
  before_filter :find_task, only: [:show, :edit, :update, :destroy, :done]

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      render @task
    else
      render text: @task.errors.full_messages.join("\n"), status: :error      
    end
  end

  def edit
  end

  def update
    @task.update_attributes(task_params)
    render json: @task
  end

  def delete
  end

  def destroy
    @task.destroy
    render nothing: true, status: :ok
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_task
    @task = Task.find(params[:id])
  end

  def done
    @task.done!
    render @task
  end

  def task_params
    params.require(:task).permit(:name, :rate, :deadline, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<h1>SIMPLE TODO LISTS</h1>
<div id="content">
  <%= yield %>
</div>
</body>
</html>

app/views/projects/_project.html.erb
<div class="project"> 
  <div class="project-header">
    <%=best_in_place(project, :name, class: 'project-name') %>
    <%= link_to image_tag('delete.png'), project_path(project), class: 'project-delete' %>
  </div>

  <%= form_for([project, Task.new], namespace: project.id, :html => {:class => 'task-add'}) do |f| %>
    <%= f.text_field :name, placeholder: "Task name", :remote => true, class: "task-name"%>
    <%= f.text_field :deadline, class: "task-deadline"%>
    <%= f.submit "Add Task" %>
  <% end %>

  <ul class="tasks sortable">
    <% project.ordered_tasks.each do |task| %>
      <%= render partial: 'tasks/task', locals: {task: task} %>
    <% end %>
  </ul>
</div> 

app/views/projects/index.html.erb
<% if user_signed_in? %>
  <li class="logout">
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

<div id="projects-container">
  <% @projects.each do |project| %>
    <%= render partial: 'projects/project', locals: {project: project} %>
  <% end %>
</div>
<div id="foot">
  <%= link_to '+ Add TODO List', new_untitled_project_path, class: 'project-add' %>
</div>

app/views/projects/new.html.erb
<h1>Add new project</h1>
<%= form_for(@project) do |f| %>

  <%= f.text_field :name, placeholder: "Project name" %>
  <%= f.submit "Add" %>

<% end %>

app/views/tasks/_task.html.erb
<li data-task-id="<%= task.id %>">
  <% if task.done? %>
    <%= check_box_tag('', set_task_done_path(task), true, disabled: true, class: 'task-done') %>
    <strike><%= task.name %></strike>
      <span class='fordeadline'>
        <strike><%= task.deadline %></strike>
      </span>
  <% else %>
    <%= check_box_tag('', set_task_done_path(task), false, disabled: false, class: 'task-done') %>
    <%= best_in_place(task, :name, url: project_task_path(task.project, task) ) %>
      <span class='fordeadline'>
        <%= best_in_place(task, :deadline, url: project_task_path(task.project, task), as: :date ) %>
      </span>
  <% end %>  

  <%= link_to image_tag('delete_sm.png'), project_task_path(task.project, task), class: 'task-delete' %>
</li>